### GET Todos
GET https://localhost:63198/todos
Content-Type: application/json
###Get Todo by ID
GET https://localhost:63198/todos/1
### Get todo active
GET https://localhost:63198/todos/active

### Post create todo
POST https://localhost:63198/todos
Content-Type: application/json

"Todo 1"


### delete delete todo
DELETE  https://localhost:63198/todos/2

### Put update todo
PUT https://localhost:63198/todos/1
Content-Type: application/json
  
  {
      "title": "Todo 1",
      "startDate": "2025-04-04T13:57:32.9189619+02:00",
      "endDate": "2025-04-04T13:57:32.9189619+02:00"
  }
